{"name": "Class ExceptionInInitializerError", "module": "java.base", "package": "java.lang", "text": "Signals that an unexpected exception has occurred in a static initializer.\n An ExceptionInInitializerError is thrown to indicate that an\n exception occurred during evaluation of a static initializer or the\n initializer for a static variable.\n\n As of release 1.4, this exception has been retrofitted to conform to\n the general purpose exception-chaining mechanism.  The \"saved throwable\n object\" that may be provided at construction time and accessed via\n the getException() method is now known as the cause,\n and may be accessed via the Throwable.getCause() method, as well\n as the aforementioned \"legacy method.\"", "codes": ["public class ExceptionInInitializerError\nextends LinkageError"], "fields": [], "methods": [{"method_name": "getException", "method_sig": "public Throwable getException()", "description": "Returns the exception that occurred during a static initialization that\n caused this error to be created.\n\n This method predates the general-purpose exception chaining facility.\n The Throwable.getCause() method is now the preferred means of\n obtaining this information."}, {"method_name": "getCause", "method_sig": "public Throwable getCause()", "description": "Returns the cause of this error (the exception that occurred\n during a static initialization that caused this error to be created)."}]}