{"name": "Interface ExceptionEvent", "module": "jdk.jdi", "package": "com.sun.jdi.event", "text": "Notification of an exception in the target VM. When an exception\n is thrown which satisfies a currently enabled\n exception request,\n an event set\n containing an instance of this class will be added\n to the VM's event queue.\n If the exception is thrown from a non-native method,\n the exception event is generated at the location where the\n exception is thrown.\n If the exception is thrown from a native method, the exception event\n is generated at the first non-native location reached after the exception\n is thrown.", "codes": ["public interface ExceptionEvent\nextends LocatableEvent"], "fields": [], "methods": [{"method_name": "exception", "method_sig": "ObjectReference exception()", "description": "Gets the thrown exception object. The exception object is\n an instance of Throwable or a subclass in the\n target VM."}, {"method_name": "catchLocation", "method_sig": "Location catchLocation()", "description": "Gets the location where the exception will be caught. An exception\n is considered to be caught if, at the point of the throw, the\n current location is dynamically enclosed in a try statement that\n handles the exception. (See the JVM specification for details).\n If there is such a try statement, the catch location is the\n first code index of the appropriate catch clause.\n \n If there are native methods in the call stack at the time of the\n exception, there are important restrictions to note about the\n returned catch location. In such cases,\n it is not possible to predict whether an exception will be handled\n by some native method on the call stack.\n Thus, it is possible that exceptions considered uncaught\n here will, in fact, be handled by a native method and not cause\n termination of the target VM. Furthermore, it cannot be assumed that the\n catch location returned here will ever be reached by the throwing\n thread. If there is\n a native frame between the current location and the catch location,\n the exception might be handled and cleared in that native method\n instead.\n \n Note that the compiler can generate try-catch blocks in some cases\n where they are not explicit in the source code; for example,\n the code generated for synchronized and\n finally blocks can contain implicit try-catch blocks.\n If such an implicitly generated try-catch is\n present on the call stack at the time of the throw, the exception\n will be considered caught even though it appears to be uncaught from\n examination of the source code."}]}