{"name": "Class InterruptedNamingException", "module": "java.naming", "package": "javax.naming", "text": "This exception is thrown when the naming operation\n being invoked has been interrupted. For example, an application\n might interrupt a thread that is performing a search. If the\n search supports being interrupted, it will throw\n InterruptedNamingException. Whether an operation is interruptible\n and when depends on its implementation (as provided by the\n service providers). Different implementations have different ways\n of protecting their resources and objects from being damaged\n due to unexpected interrupts.\n \n Synchronization and serialization issues that apply to NamingException\n apply directly here.", "codes": ["public class InterruptedNamingException\nextends NamingException"], "fields": [], "methods": []}