{"name": "Class InvocationTargetException", "module": "java.base", "package": "java.lang.reflect", "text": "InvocationTargetException is a checked exception that wraps\n an exception thrown by an invoked method or constructor.\n\n As of release 1.4, this exception has been retrofitted to conform to\n the general purpose exception-chaining mechanism.  The \"target exception\"\n that is provided at construction time and accessed via the\n getTargetException() method is now known as the cause,\n and may be accessed via the Throwable.getCause() method,\n as well as the aforementioned \"legacy method.\"", "codes": ["public class InvocationTargetException\nextends ReflectiveOperationException"], "fields": [], "methods": [{"method_name": "getTargetException", "method_sig": "public Throwable getTargetException()", "description": "Get the thrown target exception.\n\n This method predates the general-purpose exception chaining facility.\n The Throwable.getCause() method is now the preferred means of\n obtaining this information."}, {"method_name": "getCause", "method_sig": "public Throwable getCause()", "description": "Returns the cause of this exception (the thrown target exception,\n which may be null)."}]}