{"name": "Class NamingException", "module": "java.naming", "package": "javax.naming", "text": "This is the superclass of all exceptions thrown by\n operations in the Context and DirContext interfaces.\n The nature of the failure is described by the name of the subclass.\n This exception captures the information pinpointing where the operation\n failed, such as where resolution last proceeded to.\n \n Resolved Name. Portion of name that has been resolved.\n  Resolved Object. Object to which resolution of name proceeded.\n  Remaining Name. Portion of name that has not been resolved.\n  Explanation. Detail explaining why name resolution failed.\n  Root Exception. The exception that caused this naming exception\n                     to be thrown.\n\n null is an acceptable value for any of these fields. When null,\n it means that no such information has been recorded for that field.\n\n A NamingException instance is not synchronized against concurrent\n multithreaded access. Multiple threads trying to access and modify\n a single NamingException instance should lock the object.\n\n This exception has been retrofitted to conform to\n the general purpose exception-chaining mechanism.  The\n root exception (or root cause) is the same object as the\n cause returned by the Throwable.getCause() method.", "codes": ["public class NamingException\nextends Exception"], "fields": [{"field_name": "resolvedName", "field_sig": "protected\u00a0Name resolvedName", "description": "Contains the part of the name that has been successfully resolved.\n It is a composite name and can be null.\n This field is initialized by the constructors.\n You should access and manipulate this field\n through its get and set methods."}, {"field_name": "resolvedObj", "field_sig": "protected\u00a0Object resolvedObj", "description": "Contains the object to which resolution of the part of the name was\n successful. Can be null.\n This field is initialized by the constructors.\n You should access and manipulate this field\n through its get and set methods."}, {"field_name": "remainingName", "field_sig": "protected\u00a0Name remainingName", "description": "Contains the remaining name that has not been resolved yet.\n It is a composite name and can be null.\n This field is initialized by the constructors.\n You should access and manipulate this field\n through its get, set, \"append\" methods."}, {"field_name": "rootException", "field_sig": "protected\u00a0Throwable rootException", "description": "Contains the original exception that caused this NamingException to\n be thrown. This field is set if there is additional\n information that could be obtained from the original\n exception, or if the original exception could not be\n mapped to a subclass of NamingException.\n Can be null.\n\n This field predates the general-purpose exception chaining facility.\n The initCause(Throwable) and getCause() methods\n are now the preferred means of accessing this information."}], "methods": [{"method_name": "getResolvedName", "method_sig": "public Name getResolvedName()", "description": "Retrieves the leading portion of the name that was resolved\n successfully."}, {"method_name": "getRemainingName", "method_sig": "public Name getRemainingName()", "description": "Retrieves the remaining unresolved portion of the name."}, {"method_name": "getResolvedObj", "method_sig": "public Object getResolvedObj()", "description": "Retrieves the object to which resolution was successful.\n This is the object to which the resolved name is bound."}, {"method_name": "getExplanation", "method_sig": "public String getExplanation()", "description": "Retrieves the explanation associated with this exception."}, {"method_name": "setResolvedName", "method_sig": "public void setResolvedName (Name name)", "description": "Sets the resolved name field of this exception.\n\nname is a composite name. If the intent is to set\n this field using a compound name or string, you must\n \"stringify\" the compound name, and create a composite\n name with a single component using the string. You can then\n invoke this method using the resulting composite name.\n\n A copy of name is made and stored.\n Subsequent changes to name do not\n affect the copy in this NamingException and vice versa."}, {"method_name": "setRemainingName", "method_sig": "public void setRemainingName (Name name)", "description": "Sets the remaining name field of this exception.\n\nname is a composite name. If the intent is to set\n this field using a compound name or string, you must\n \"stringify\" the compound name, and create a composite\n name with a single component using the string. You can then\n invoke this method using the resulting composite name.\n\n A copy of name is made and stored.\n Subsequent changes to name do not\n affect the copy in this NamingException and vice versa."}, {"method_name": "setResolvedObj", "method_sig": "public void setResolvedObj (Object obj)", "description": "Sets the resolved object field of this exception."}, {"method_name": "appendRemainingComponent", "method_sig": "public void appendRemainingComponent (String name)", "description": "Add name as the last component in remaining name."}, {"method_name": "appendRemainingName", "method_sig": "public void appendRemainingName (Name name)", "description": "Add components from 'name' as the last components in\n remaining name.\n\nname is a composite name. If the intent is to append\n a compound name, you should \"stringify\" the compound name\n then invoke the overloaded form that accepts a String parameter.\n\n Subsequent changes to name do not\n affect the remaining name field in this NamingException and vice versa."}, {"method_name": "getRootCause", "method_sig": "public Throwable getRootCause()", "description": "Retrieves the root cause of this NamingException, if any.\n The root cause of a naming exception is used when the service provider\n wants to indicate to the caller a non-naming related exception\n but at the same time wants to use the NamingException structure\n to indicate how far the naming operation proceeded.\n\n This method predates the general-purpose exception chaining facility.\n The getCause() method is now the preferred means of obtaining\n this information."}, {"method_name": "setRootCause", "method_sig": "public void setRootCause (Throwable e)", "description": "Records the root cause of this NamingException.\n If e is this, this method does not do anything.\n\n This method predates the general-purpose exception chaining facility.\n The initCause(Throwable) method is now the preferred means\n of recording this information."}, {"method_name": "getCause", "method_sig": "public Throwable getCause()", "description": "Returns the cause of this exception.  The cause is the\n throwable that caused this naming exception to be thrown.\n Returns null if the cause is nonexistent or\n unknown."}, {"method_name": "initCause", "method_sig": "public Throwable initCause (Throwable cause)", "description": "Initializes the cause of this exception to the specified value.\n The cause is the throwable that caused this naming exception to be\n thrown.\n\n This method may be called at most once."}, {"method_name": "toString", "method_sig": "public String toString()", "description": "Generates the string representation of this exception.\n The string representation consists of this exception's class name,\n its detailed message, and if it has a root cause, the string\n representation of the root cause exception, followed by\n the remaining name (if it is not null).\n This string is used for debugging and not meant to be interpreted\n programmatically."}, {"method_name": "toString", "method_sig": "public String toString (boolean detail)", "description": "Generates the string representation in more detail.\n This string representation consists of the information returned\n by the toString() that takes no parameters, plus the string\n representation of the resolved object (if it is not null).\n This string is used for debugging and not meant to be interpreted\n programmatically."}]}