{"name": "Class PrivilegedActionException", "module": "java.base", "package": "java.security", "text": "This exception is thrown by\n doPrivileged(PrivilegedExceptionAction) and\n doPrivileged(PrivilegedExceptionAction,\n AccessControlContext context) to indicate\n that the action being performed threw a checked exception.  The exception\n thrown by the action can be obtained by calling the\n getException method.  In effect, an\n PrivilegedActionException is a \"wrapper\"\n for an exception thrown by a privileged action.\n\n As of release 1.4, this exception has been retrofitted to conform to\n the general purpose exception-chaining mechanism.  The \"exception thrown\n by the privileged computation\" that is provided at construction time and\n accessed via the getException() method is now known as the\n cause, and may be accessed via the Throwable.getCause()\n method, as well as the aforementioned \"legacy method.\"", "codes": ["public class PrivilegedActionException\nextends Exception"], "fields": [], "methods": [{"method_name": "getException", "method_sig": "public Exception getException()", "description": "Returns the exception thrown by the privileged computation that\n resulted in this PrivilegedActionException.\n\n This method predates the general-purpose exception chaining facility.\n The Throwable.getCause() method is now the preferred means of\n obtaining this information."}, {"method_name": "getCause", "method_sig": "public Throwable getCause()", "description": "Returns the cause of this exception (the exception thrown by\n the privileged computation that resulted in this\n PrivilegedActionException)."}]}