{"name": "Class URIReferenceException", "module": "java.xml.crypto", "package": "javax.xml.crypto", "text": "Indicates an exceptional condition thrown while dereferencing a\n URIReference.\n\n A URIReferenceException can contain a cause: another\n throwable that caused this URIReferenceException to get thrown.", "codes": ["public class URIReferenceException\nextends Exception"], "fields": [], "methods": [{"method_name": "getURIReference", "method_sig": "public URIReference getURIReference()", "description": "Returns the URIReference that was being dereferenced\n when the exception was thrown."}, {"method_name": "getCause", "method_sig": "public Throwable getCause()", "description": "Returns the cause of this URIReferenceException or\n null if the cause is nonexistent or unknown.  (The\n cause is the throwable that caused this\n URIReferenceException to get thrown.)"}, {"method_name": "printStackTrace", "method_sig": "public void printStackTrace()", "description": "Prints this URIReferenceException, its backtrace and\n the cause's backtrace to the standard error stream."}, {"method_name": "printStackTrace", "method_sig": "public void printStackTrace (PrintStream s)", "description": "Prints this URIReferenceException, its backtrace and\n the cause's backtrace to the specified print stream."}, {"method_name": "printStackTrace", "method_sig": "public void printStackTrace (PrintWriter s)", "description": "Prints this URIReferenceException, its backtrace and\n the cause's backtrace to the specified print writer."}]}