{"name": "Class WriteAbortedException", "module": "java.base", "package": "java.io", "text": "Signals that one of the ObjectStreamExceptions was thrown during a\n write operation.  Thrown during a read operation when one of the\n ObjectStreamExceptions was thrown during a write operation.  The\n exception that terminated the write can be found in the detail\n field. The stream is reset to it's initial state and all references\n to objects already deserialized are discarded.\n\n As of release 1.4, this exception has been retrofitted to conform to\n the general purpose exception-chaining mechanism.  The \"exception causing\n the abort\" that is provided at construction time and\n accessed via the public detail field is now known as the\n cause, and may be accessed via the Throwable.getCause()\n method, as well as the aforementioned \"legacy field.\"", "codes": ["public class WriteAbortedException\nextends ObjectStreamException"], "fields": [{"field_name": "detail", "field_sig": "public\u00a0Exception detail", "description": "Exception that was caught while writing the ObjectStream.\n\n This field predates the general-purpose exception chaining facility.\n The Throwable.getCause() method is now the preferred means of\n obtaining this information."}], "methods": [{"method_name": "getMessage", "method_sig": "public String getMessage()", "description": "Produce the message and include the message from the nested\n exception, if there is one."}, {"method_name": "getCause", "method_sig": "public Throwable getCause()", "description": "Returns the exception that terminated the operation (the cause)."}]}